### ISSUE TITLE
file.go File: поле Name имеет тип bool

### ISSUE THREAD

**Issue by Zherdev** [mail-ru-im/bot-golang#13]
При вызове метода Bot.GetFileInfo с корректным fileId всегда возвращается ошибка "error while unmarshalling information: ...", т.к.  в структуре File поле Name имеет тип bool, а метод API ICQ /files/getInfo возвращает в поле filename строку. 

См. схему на https://icq.com/botapi/#/files/get_files_getInfo

file.go
```
type File struct {
	// Id of the file
	ID string `json:"fileId"`

	// Type of the file
	Type string `json:"type"`

	// Size in bytes
	Size uint64 `json:"size"`

	// Name of file
	Name bool `json:"filename"`

	// URL to the file
	URL string `json:"url"`
}
```

при замене типа на string ошибка уходит.

**Comment by gabolaev** [comment]
Действительно, спасибо за репорт. Исправим в ближайшее время
